apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nodeapp.fullname" . }}-secret
  labels:
    {{- include "nodeapp.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.postgresql.password | b64enc }}